Repository FourTeamProject/pikachu_tdd, pull requests merged in 2020-06, with the labels that each got.

#3 개행 추가
  src/main/java/reference_code/client/ShopMain.java
Labels: 이슈사항

#6 개행 추가
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/type/CustomerType.java
Labels: 이슈사항

#7 개행추가
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/CustomerTest.java
Labels: 수업

#5 개행 추가
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/Customer.java
Labels: 이슈사항

#10 요구사항 추가 및 패키지 구분
  FourTeam 요구사항.md
Labels: 수업

#12 거래거절 고객 추가 및 테스트 추가
  pom.xml
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/Customer.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/OrderSheet.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/type/CustomerType.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/CustomerTest.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/OrderSheetTest.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/PaymentTest.java
  src/test/java/com/github/fourteam/sample/MockitoTest.java
Labels: 과제

#13 1주차 과제
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/exception/RequiredValueException.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/client/ShopMain.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/Customer.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/CustomerFactory.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/ExcutiveCustomer.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/GeneralCustomer.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/RejectCustomer.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/SuperCustomer.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/login/Login.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/order/OrderService.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/order/OrderServiceImpl.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/payment/Payment.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/BuilderProduct.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/IMac.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/MacBook.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/Product.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/ProductFactory.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/product/ProductPrint.java
  src/test/java/com/github/fourteam/pikachu/week1/imesung/CustomerTest.java
Labels: 과제

#19 인증객체 사용
  src/test/java/com/github/fourteam/pikachu/week1/junwoo/impl/GeneralCustomerAuthorityCheckImplTest.java
  src/test/java/com/github/fourteam/sample/MockitoTest.java
Labels: 제안

#28 2주차 과제 제출
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/GiftProduct.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/Product.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/impl/NullProduct.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/impl/SalesGift.java
  src/main/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/impl/SalesProduct.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/customer/impl/SupplierEmployeeTest.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/SalesGiftTest.java
  src/test/java/com/github/fourteam/pikachu/week1/bbubbush/domain/product/SalesProductTest.java
  src/test/java/com/github/fourteam/sample/AnnotationMockTest.java
Labels: 과제

#38 3주차 요구사항
  FourTeam 요구사항.md
Labels: 과제

#39 3주차 요구사항 수정
  FourTeam 요구사항.md
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/CustType.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/customer/CustomerType.java
  src/main/java/com/github/fourteam/pikachu/week1/imesung/domain/order/OrderSheet.java
  src/test/java/com/github/fourteam/pikachu/week1/imesung/OrderSheetTest.java
Labels: 과제
